weights: /content/drive/MyDrive/Data/Simulations/yolov5s/weights/last.pt
cfg: ''
data: data/vessels_dataset_reduced.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 300
batch_size: 32
imgsz: 800
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /content/drive/MyDrive/Data/Simulations
name: yolov5s
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /content/drive/MyDrive/Data/Simulations/yolov5s
