name: SARveillance-conda-env
dependencies:
  - python==3.9
  - pip
  - proj==7.2.0
  - glob2
  - conda-forge::cartopy
  - conda-forge::openblas
  - conda-forge::earthengine-api
  - pip:
    - scipy
    - numpy==1.22.0
    - pyproj==3.2.1
    - geemap==0.11.0
    - pandas==1.3.5
    - streamlit
    - shapely==1.7.1